# Site settings
title: Hillsborough County Communications &amp; Digital Media
email: webrequest@hillsboroughcounty.org

description:

baseurl: "/CDN" # the subpath of your site, e.g. /blog/

# url: "http://yourdomain.com" # the base hostname & protocol for your site

# twitter_username: jekyllrb
# github_username:  jekyll

collections:
   sw_days:
      output: false

# Build settings
markdown: kramdown

gems:
 - jekyll-coffeescript
 - jekyll-paginate
